# -*- coding: utf-8 -*-
"""Customer Churn Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOtgnzkWOkMgkIHF4Uf0-aCkmJJrTqfk
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)

data={
    "Customer_ID":np.random.randint(1, 100000, size=100000),
    "Age":np.random.randint(18, 65, size=100000),
    "Gender":np.random.choice(["Male","Female"], size=100000),
    "Tenure":np.random.randint(1, 10, size=100000),
    "Balance":np.random.randint(1000, 100000, size=100000),
    "CreditScore":np.random.randint(300, 850, size=100000),
    "Estimatedsalary":np.random.randint(20000, 100000, size=100000),
    "Numofproducts":np.random.randint(1, 5, size=100000),
    "IsActivateMember":np.random.choice([0,1], size=100000),
    "Churn":np.random.choice([0,1], size=100000)
}

df=pd.DataFrame(data)

df

pip install faker

from faker import Faker
fake=Faker()
df["name"]=[fake.name() for _ in range(len(df))]
df

"""# Data Cleaning & Preprocessing"""

print(df.isnull().sum())
print(df.dtypes)
df["Gender"] = data["Gender"]
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1}).astype(int)

"""# Descriptive Statistics"""

print(df.describe())
print("Mean:\n", df.mean(numeric_only=True))
print("Median:\n", df.median(numeric_only=True))
print("Mode:\n", df.mode().iloc[0])
print("Standard Deviation:\n", df.std(numeric_only=True))

"""# Churn Behavior Analysis"""

print("Churn Percentage:", df["Churn"].mean() * 100)
churn_group = df.groupby("Churn").mean(numeric_only=True)
print(churn_group)

"""# Group-Based Analysis"""

df["AgeGroup"] = pd.cut(df["Age"], bins=[18,30,45,60,70], labels=["18-30","30-45","45-60","60+"])
print(pd.crosstab(df["AgeGroup"], df["Churn"]))
print(pd.crosstab(df["Gender"], df["Churn"]))
print(pd.crosstab(df["IsActivateMember"], df["Churn"]))
print(pd.crosstab(df["Numofproducts"], df["Churn"]))

"""# Relationship Analysis"""

corr = df.corr(numeric_only=True)
print(corr)

"""# Bar chart"""

sns.countplot(x="Churn",
              data=df,
              color='red')
plt.title("Churn Count")
plt.legend(title="Churn")
plt.show()

"""# Pie chart"""

df["Churn"].value_counts().plot.pie(autopct="%1.1f%%")
plt.title("Churn Distribution")
plt.legend(title="Churn")
plt.show()

"""# Histogram"""

df["Age"].hist(),
color='red',
bins=10,
plt.title("Age Distribution")
plt.legend(title="Age")
plt.show()

"""# Scatter plot"""

plt.scatter(df["Balance"], df["CreditScore"])
plt.xlabel("Balance")
plt.ylabel("Credit Score")
plt.title("Balance vs Credit Score")
plt.legend()
plt.show()

"""# Box plot"""

sns.boxplot(x="Churn", y="Balance", data=df)
plt.title("Balance vs Churn")
plt.show()

"""# Heat map"""

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""# Insights"""

high_risk = df[(df["Balance"] > 120000) & (df["IsActivateMember"] == 0)]
print("High Risk Customers:", len(high_risk))
low_credit = df[df["CreditScore"] < 500]
print("Low Credit Customers:", len(low_credit))